-- Generated by Creer at 04:49PM on November 01, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
-- This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

local class = require("joueur.utilities.class")
local GameObject = require("games.anarchy.gameObject")

-- <<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- you can add addtional require(s) here
-- <<-- /Creer-Merge: requires -->>

--- @class Player: A player in this game. Every AI controls one player.
local Player = class(GameObject)

--- initializes a Player with basic logic as provided by the Creer code generator
function Player:init(...)
    GameObject.init(self, ...)

    -- The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

    -- How many bribes this player has remaining to use during their turn. Each action a Building does costs 1 bribe. Any unused bribes are lost at the end of the player's turn.
    self.bribesRemaining = 0
    -- All the buildings owned by this player.
    self.buildings = Table()
    -- What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
    self.clientType = ""
    -- All the FireDepartments owned by this player.
    self.fireDepartments = Table()
    -- The Warehouse that serves as this player's headquarters and has extra health. If this gets destroyed they lose.
    self.headquarters = nil
    -- if the player lost the game or not
    self.lost = false
    -- The name of the player
    self.name = "Anonymous"
    -- this player's opponent in the game.
    self.otherPlayer = nil
    -- All the PoliceDepartments owned by this player.
    self.policeDepartments = Table()
    -- the reason why the player lost the game
    self.reasonLost = ""
    -- the reason why the player won the game
    self.reasonWon = ""
    -- The amount of time (in ns) remaining for this AI to send commands.
    self.timeRemaining = 0
    -- All the warehouses owned by this player. Includes the Headquarters.
    self.warehouses = Table()
    -- All the WeatherStations owned by this player.
    self.weatherStations = Table()
    -- if the player won the game or not
    self.won = false
end


-- <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- if you want to add any client side logic (such as state checking functions) this is where you can add them
-- <<-- /Creer-Merge: functions -->>

return Player
