-- Generated by Creer at 10:46PM on October 16, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
-- This is a simple class to represent the WeatherStation object in the game. You can extend it by adding utility functions here in this file.

local class = require("joueur.utilities.class")
local Building = require("games.anarchy.building")

-- <<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- you can add addtional require(s) here
-- <<-- /Creer-Merge: requires -->>

--- @class WeatherStation: Can be bribed to change the next Forecast in some way.
local WeatherStation = class(Building)

--- initializes a WeatherStation with basic logic as provided by the Creer code generator
function WeatherStation:init(...)
    Building.init(self, ...)

    -- The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

end

--- Bribe the weathermen to intensity the next Forecast by 1 or -1
-- @param {boolean} negative: By default the intensity will be increased by 1, setting this to true decreases the intensity by 1.
-- @returns <boolean> true if the intensity was changed, false otherwise
function WeatherStation:intensify(negative)
    return not not (self:_runOnServer("intensify", {
        negative = negative,
    }))
end
--- Bribe the weathermen to change the direction of the next Forecast by rotating it clockwise or counterclockwise.
-- @param {boolean} counterclockwise: By default the direction will be rotated clockwise. If you set this to true we will rotate the forecast counterclockwise instead.
-- @returns <boolean> true if the rotation worked, false otherwise.
function WeatherStation:rotate(counterclockwise)
    return not not (self:_runOnServer("rotate", {
        counterclockwise = counterclockwise,
    }))
end

-- <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- if you want to add any client side logic (such as state checking functions) this is where you can add them
-- <<-- /Creer-Merge: functions -->>

return WeatherStation
