-- Generated by Creer at 02:43AM on May 03, 2015 UTC, git hash: '2acbba9c4b682c4de68840c1ca9bec631e9c635f'
-- This is a simple class to represent the Checker object in the game. You can extend it by adding utility functions here in this file.

local class = require("utilities.class")
local GameObject = require("Checkers.gameObject")

--- @class Checker: A checker on the game board.
local Checker = class(GameObject)

--- initializes a Checker with basic logic as provided by the Creer code generator
function Checker:init(...)
    GameObject.init(self, ...)

    -- The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

    -- The player that controls this Checker.
    self.owner = nil
    -- The y coordinate of the checker.
    self.y = 0
    -- If the checker has been kinged and can move backwards.
    self.kinged = false
    -- The x coordinate of the checker.
    self.x = 0
end

--- returns if the checker is owned by your player or not
-- @returns <boolean> true if it is yours, false if it is not yours
function Checker:isMine()
    return not not (self._client:runOnServer(self, "isMine", {
    }))
end
--- Moves the checker from its current location to the given (x, y).
-- @param <number> x: The x coordinate to move to.
-- @param <number> y: The y coordinate to move to.
-- @returns <Checker> Returns the same checker that moved if the move was successful. null otherwise.
function Checker:move(x, y)
    return (self._client:runOnServer(self, "move", {
        x = x,
        y = y,
    }))
end

return Checker
