-- Generated by Creer, git hash c6767247662bdc8024518de1aebc87bcf634ca49
-- This is a simple class to represent the Checker object in the game. You can extend it by adding utility functions here in this file.

local class = require("utilities.class")
local GameObject = require("Checkers.gameObject")

--- @class Checker: A checker on the game board.
local Checker = class(GameObject)

--- initializes a Checker with basic logic as provided by the Creer code generator
-- @param <table> data: initialization data
function Checker:init(data)
    GameObject.init(self, data)

    if data.y == nil then -- set to default value because it was not sent
        self.y = 0
    else
        self.y = tonumber(data.y)
    end

    if data.kinged == nil then -- set to default value because it was not sent
        self.kinged = false
    else
        self.kinged = (data.kinged)
    end

    if data.owner == nil then -- set to default value because it was not sent
        self.owner = nil
    else
        self.owner = (data.owner)
    end

    if data.x == nil then -- set to default value because it was not sent
        self.x = 0
    else
        self.x = tonumber(data.x)
    end

end


--- Moves the checker from its current location to the given (x, y).
-- @param <int> x: The x coordinate to move to.
-- @param <int> y: The y coordinate to move to.
function Checker:move(x, y)
    return self._client:sendCommand(self, "move", {
        x = x,
        y = y,
    })
end

return Checker
