-- Generated by Creer at 02:43AM on May 03, 2015 UTC, git hash: '2acbba9c4b682c4de68840c1ca9bec631e9c635f'
-- This is a simple class to represent the Game object in the game. You can extend it by adding utility functions here in this file.

local class = require("utilities.class")
local BaseGame = require("baseGame")

--- @class Game: The simple version of American Checkers. An 8x8 board with 12 checkers on each side that must move diagonally to the opposing side until kinged. Very simple.
local Game = class(BaseGame)

--- initializes a Game with basic logic as provided by the Creer code generator
function Game:init(...)
    BaseGame.init(self, ...)

    -- The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

    -- All the checkers currently in the game.
    self.checkers = {}
    -- A mapping of every game object's ID to the actual game object. Primarily used by the server and client to easily refer to the game objects via ID.
    self.gameObjects = {}
    -- If the last checker that moved jumped, meaning it can move again.
    self.checkerMovedJumped = false
    -- List of all the players in the game.
    self.players = {}
    -- The player whose turn it is currently. That player can send commands. Other players cannot.
    self.currentPlayer = nil
    -- The current turn number, starting at 0 for the first player's turn
    self.currentTurn = None
    -- The maximum number of turns before the game will automatically end.
    self.maxTurns = None
    -- The width of the board for X component of a checker.
    self.boardWidth = None
    -- The height of the board for the Y component of a checker.
    self.boardHeight = None
    -- The checker that last moved and must be moved because only one checker can move during each players turn.
    self.checkerMoved = nil

    self.name = "Checkers"

    self._gameObjectClasses = {
        GameObject = require("Checkers.gameObject"),
        Player = require("Checkers.player"),
        Checker = require("Checkers.checker"),
    }
end


return Game
