-- Generated by Creer at 02:43AM on May 03, 2015 UTC, git hash: '2acbba9c4b682c4de68840c1ca9bec631e9c635f'
-- This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

local class = require("utilities.class")
local GameObject = require("Checkers.gameObject")

--- @class Player: A player in this game. Every AI controls one player.
local Player = class(GameObject)

--- initializes a Player with basic logic as provided by the Creer code generator
function Player:init(...)
    GameObject.init(self, ...)

    -- The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

    -- The name of the player
    self.name = "Anonymous"
    -- All the checkers currently in the game owned by this player
    self.checkers = {}
    -- the reason why the player won the game
    self.reasonWon = ""
    -- if the player lost the game or not
    self.lost = false
    -- if the player won the game or not
    self.won = false
    -- The direction your checkers must go along the y-axis until kinged
    self.yDirection = 0
    -- What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
    self.clientType = ""
    -- The amount of time (in ms) remaining for this AI to send commands.
    self.timeRemaining = 0
    -- the reason why the player lost the game
    self.reasonLost = ""
end


return Player
