-- Generated by Creer at 02:59AM on August 12, 2015 UTC, git hash: '44abe78df9634b90415f2d1791a923bdc6e4f5c6'
-- This is a simple class to represent the Checker object in the game. You can extend it by adding utility functions here in this file.

local class = require("utilities.class")
local GameObject = require("games.checkers.gameObject")

-- <<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- you can add addtional require(s) here
-- <<-- /Creer-Merge: requires -->>

--- @class Checker: A checker on the game board.
local Checker = class(GameObject)

--- initializes a Checker with basic logic as provided by the Creer code generator
function Checker:init(...)
    GameObject.init(self, ...)

    -- The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

    -- If the checker has been kinged and can move backwards.
    self.kinged = false
    -- The player that controls this Checker.
    self.owner = nil
    -- The x coordinate of the checker.
    self.x = 0
    -- The y coordinate of the checker.
    self.y = 0
end

--- returns if the checker is owned by your player or not
-- @returns <boolean> true if it is yours, false if it is not yours
function Checker:isMine()
    return not not (self:_runOnServer("isMine", {
    }))
end
--- Moves the checker from its current location to the given (x, y).
-- @param {number} x: The x coordinate to move to.
-- @param {number} y: The y coordinate to move to.
-- @returns <Checker> Returns the same checker that moved if the move was successful. null otherwise.
function Checker:move(x, y)
    return (self:_runOnServer("move", {
        x = x,
        y = y,
    }))
end

-- <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- if you want to add any client side logic (such as state checking functions) this is where you can add them
-- <<-- /Creer-Merge: functions -->>

return Checker
