-- Generated by Creer at 07:08PM on October 21, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
-- This is a simple class to represent the Player object in the game. You can extend it by adding utility functions here in this file.

local class = require("joueur.utilities.class")
local GameObject = require("games.checkers.gameObject")

-- <<-- Creer-Merge: requires -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- you can add addtional require(s) here
-- <<-- /Creer-Merge: requires -->>

--- @class Player: A player in this game. Every AI controls one player.
local Player = class(GameObject)

--- initializes a Player with basic logic as provided by the Creer code generator
function Player:init(...)
    GameObject.init(self, ...)

    -- The following values should get overridden when delta states are merged, but we set them here as a reference for you to see what variables this class has.

    -- All the checkers currently in the game owned by this player
    self.checkers = Table()
    -- What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
    self.clientType = ""
    -- if the player lost the game or not
    self.lost = false
    -- The name of the player
    self.name = "Anonymous"
    -- the reason why the player lost the game
    self.reasonLost = ""
    -- the reason why the player won the game
    self.reasonWon = ""
    -- The amount of time (in ns) remaining for this AI to send commands.
    self.timeRemaining = 0
    -- if the player won the game or not
    self.won = false
    -- The direction your checkers must go along the y-axis until kinged
    self.yDirection = 0
end


-- <<-- Creer-Merge: functions -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
-- if you want to add any client side logic (such as state checking functions) this is where you can add them
-- <<-- /Creer-Merge: functions -->>

return Player
